monolog:
    channels: ['markdown', 'security']
#    handlers:
#        security:
#            level: debug
#            type: stream
#            channels: ['api']
#            path: '%env(API_LOG)%'
