twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
        - 'form/custom_email.html.twig'

    globals:
        sitename: '%env(SITE_NAME)%'

when@test:
    twig:
        strict_variables: true
