# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.support_email: '%env(SUPPORT_EMAIL)%'
    app.example_enabled: '%env(bool:EXAMPLE_ENABLED)%'
    app.mark_as_bold: '%env(bool:MARK_ARTICLE_WORDS_WITH_BOLD)%'
    cache_adapter: cache.adapter.filesystem

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $debug: '%kernel.debug%'
            Demontpx\ParsedownBundle\Parsedown: '@demontpx_parsedown.parsedown'
            $markAsBold: '%env(bool:MARK_ARTICLE_WORDS_WITH_BOLD)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
